# This file is regenerated by .github/workflows/release.yml on every tag.
# Editing it manually has no effect after the next release.
class Hyprmon < Formula
  desc "Hyprland-style system monitor widget for macOS"
  homepage "https://github.com/pipe0919/hyprmon"
  url "https://github.com/pipe0919/hyprmon/releases/download/v0.0.0/placeholder.tar.gz"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  license "Apache-2.0"

  depends_on macos: :sonoma

  def install
    prefix.install Dir["Hyprmon.app"]
    bin.write_exec_script prefix/"Hyprmon.app/Contents/MacOS/hyprmon"
  end

  test do
    system bin/"hyprmon", "--version"
  end
end
